- name: Catalogue Configuration
  hosts: catalogue
  become: yes
  tasks:
    - name: Disableing nodejs default module
      ansible.builtin.command: dnf disable nodejs:20 -y

    - name: Installing nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: present

    - name: Create system user
      ansible.builtin.user:
        name: roboshop
        system: true
        home: /app
        shell: /sbin/nologin
        Comment: "Roboshop system user"

    - name: Create the app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Download Catalogue
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
        dest: /tmp/catalogue.zip

    - name: Unzip Catalogue
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app
        remote_src: yes

    - name: Install nodejs dependencies
      community.general.npm:
        path: /app

    - name: copy catalogue service file
      ansible.builtin.copy:
        src: catalogue.service
        dest: /etc/systemd/system/catalogue.service

    - name: copy mongo repo
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: Install Mongodb client
      ansible.builtin.dnf:
        name: mongodb-mongosh
        state: present
    - name: Check Mongodb data loaded or not
      ansible.builtin.command: mongosh --host "{{ MONGODB_HOST }}" --quiet  --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
      register: Catalogue_outpu

    - name: Print the Catalogue output
      ansible.builtin.debug:
        msg: "{{ Catalogue_outpu }}"
